plugins {
	id 'org.springframework.boot' version '3.0.0'
	id 'io.spring.dependency-management' version '1.1.0'
	id 'java'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '18'

repositories {
	mavenCentral()
}

dependencies {
	// tag::actuator[]
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	// end::actuator[]
	implementation 'org.springframework.boot:spring-boot-starter-web'

	// Lombok dependency for code compilation
    compileOnly 'org.projectlombok:lombok:1.18.36'
    // Lombok annotation processor for code generation
    annotationProcessor 'org.projectlombok:lombok:1.18.36'

	// JPA
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

	// tag::tests[]
	testImplementation('org.springframework.boot:spring-boot-starter-test')
	testCompileOnly 'org.projectlombok:lombok:1.18.36'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.36'
	// end::tests[]
}

test {
	useJUnitPlatform()
}
